# -*- coding: utf-8 -*-
"""gallup_with_sampling_neurips.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlVJIXeaCwjt82WoHfH57QvCREfyY5c4

# One feature to one outcome

## Imports
"""

import sys
import os
import gc
import time
from IPython.display import clear_output
from copy import deepcopy

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr, kstest, ks_2samp, entropy, chisquare, power_divergence
from scipy.spatial import distance
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from tqdm import tqdm
from tqdm.contrib import tzip
from numba import jit

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

np.set_printoptions(linewidth=120, suppress=True)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# DEVICE = torch.device('cpu')
DEVICE

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
#%cd '/content/gdrive/MyDrive/HLAB/post_strat_nn'
# %cd '/content/gdrive/MyDrive/post_strat_nn'

"""## Load all CSVs

`county_outcomes` is the gallup scores per county

`county_features` is the census percentages for age, gender, income, and education bins

`user_features` is each twitter user's predicted socio-demographics (age, gender, income, education), language predictions (DEP_SCORE, ANX_SCORE, etc), and the weight from the original post-stratification weight creation process

The user income is logged so it must be unlogged
"""

GALLUP = False
TWITTER = True
VOTING = False

if GALLUP:
    spatial_group = "cnty"
    person_file_name = 'gallup_user_table.csv'
    person_outcomes = []
    outcome_file_name = 'gallup_scores.csv'
    spatial_outcomes = ['depression', 'worried', 'happy', 'ladder']
if TWITTER:
    spatial_group = "cnty"
    person_file_name = 'twitter_user_table.csv'
    person_outcomes = ['DEP_SCORE', 'ANX_SCORE', 'SWB_HAPPY', 'SWB_LADDER']
    outcome_file_name = 'twitter_cnty_scores.csv'
    spatial_outcomes = ['depression', 'worried', 'happy', 'ladder']
if VOTING:
    spatial_group = "GEOID20"
    person_file_name = "voting_data_florida_user.csv"
    person_outcomes = ['registered_repub']
    outcome_file_name = 'voting_data_florida_GEOID20.csv'
    spatial_outcomes = ['repub_perc']

# outcome_file_name = 'gallup_scores.csv'

"""## Demographic bins

We establish the necessary bins for each of the socio-demographic factors. The bin labels must correspond to the census columns. The twitter bins are the bin boundaries.
"""

if GALLUP or TWITTER:
    DEMOGRAPHICS = ['age', 'inc', 'gen', 'edu']

    BIN_LABELS = {
        'age': ['15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64', '65+'],
        # 'age': ['15-24', '25-49', '50+'],
        # 'age': ['15-19', '20-39', '50-54', '55+'],
        'inc': ['0-10k', '10k-15k', '15k-25k', '25k-35k', '35k-50k', '50k-75k', '75k-100k', '100k-150k', '150k-200k', '200k+'],
        # 'inc': ['0-35k', '35k-75k', '75k+'],
        'gen': ['male', 'female'],
        'edu': ['high_school', 'college'],
    }

    TWITTER_BINS = {
        'age': [0, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 100],
        # 'age': [-np.inf, 25, 50, np.inf],
        # 'age': [-np.inf, 20, 40, 55, np.inf],
        'inc': [-np.inf, 10000, 15000, 25000, 35000, 50000, 75000, 100000, 150000, 200000, np.inf],
        # 'inc': [-np.inf, 35000, 75000, np.inf],
        'gen': [-np.inf, 0, np.inf],
        'edu': [0, 1, 5],
    }

    CENSUS_TABLE_COLS = {
        'age': ['total_15to19', 'total_20to24', 'total_25to29', 'total_30to34', 'total_35to39', 'total_40to44', 'total_45to49', 'total_50to54', 'total_55to59', 'total_60to64', 'total_65plus'],
        # 'age': ['total_15to24', 'total_25to49', 'total_50plus'],
        # 'age:' ['total_15to19', 'total_20to39', 'total_40to54', 'total_55plus'],
        'inc': ['incomelt10k', 'income10kto14999', 'income15kto24999', 'income25kto34999', 'income35kto49999', 'income50kto74999', 'income75kto99999', 'income100kto149999', 'income150kto199999', 'incomegt200k'],
        # 'inc': ['income0to34999', 'income35kto74999', 'incomegt75k'],
        'gen': ['male_perc', 'female_perc'],
        'edu': ['perc_high_school_or_higher', 'perc_bach_or_higher'],
    }

if VOTING:
    DEMOGRAPHICS = ['age', 'gen', 'married']
    BIN_LABELS = {
        'age': ['18-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80-84', '85+'],
        'gen': ['male', 'female'],
        'married': ['not_married', 'married'],
    }
    TWITTER_BINS = {
        'age': [0, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 100],
        'gen': [0, 1, 5],
        'married': [0, 1, 5],
    }
    CENSUS_TABLE_COLS = {
        'age': ['vote_age_18_to_19_years_perc', 'vote_age_20_to_24_years_perc', 'vote_age_25_to_29_years_perc', 'vote_age_30_to_34_years_perc', 'vote_age_35_to_39_years_perc', 'vote_age_40_to_44_years_perc', 'vote_age_45_to_49_years_perc', 'vote_age_50_to_54_years_perc', 'vote_age_55_to_59_years_perc', 'vote_age_60_to_64_years_perc', 'vote_age_65_to_69_years_perc', 'vote_age_70_to_74_years_perc', 'vote_age_75_to_79_years_perc', 'vote_age_80_to_84_years_perc', 'vote_age_85plus_years_perc'],
        'gen': ['male_perc', 'female_perc'],
        'married': ['not_married_perc', 'married_perc'],
    }

COUNTY_OUTCOMES_DF = pd.read_csv(outcome_file_name)
COUNTY_OUTCOMES_DF.set_index(spatial_group, inplace=True)
COUNTY_OUTCOMES_DF.head() # already cleaned

#spatial_outcomes = list(COUNTY_OUTCOMES_DF.columns)

CENSUS_DEMOGRAPHICS_DF = pd.read_csv('census_acs2015_5yr_demographics.csv')
CENSUS_DEMOGRAPHICS_DF.set_index(spatial_group, inplace=True)
CENSUS_DEMOGRAPHICS_DF.head() # already cleaned

#USER_FACTORS_AND_FEATURES_DF = pd.read_csv('user_table_redist.csv')
USER_FACTORS_AND_FEATURES_DF = pd.read_csv(person_file_name)
USER_FACTORS_AND_FEATURES_DF.set_index(spatial_group, inplace=True)
USER_FACTORS_AND_FEATURES_DF['ops_weight'] = 1
USER_FACTORS_AND_FEATURES_DF.rename(columns={'icwsm_weight': 'rps_weight'}, inplace=True)
USER_FACTORS_AND_FEATURES_DF.head() # already cleaned

"""## Test Pearson r and MSE for unweighted and ICWSM weights

### Unweighted
"""

n = -1 # number of samples to take from each county
frac = -1 # percentage (rather than count) of observations to take from each county
N_iters = 10 # number of time to do unweighted calculation


def weighted_calculation(data, n=-1, frac=0, weight_col=None):
    rs, mses = [], []
    for person_feat, spatial_var in zip(person_outcomes, spatial_outcomes):
        if weight_col:
            weighted_users = data[person_feat] * data[weight_col]
            if n > 0:
                aggregated = weighted_users.groupby(spatial_group).sample(n).groupby(spatial_group).mean()
            elif frac > 0:
              aggregated = weighted_users.groupby(spatial_group).sample(frac=frac).groupby(spatial_group).mean()
            else:
                aggregated = weighted_users.groupby(spatial_group).mean()
            aggregated.name = person_feat
        else: # weights all = 1
            if n > 0:
                aggregated = data[person_feat].groupby(spatial_group).sample(n).groupby(spatial_group).mean()
            elif frac > 0:
                aggregated = data[person_feat].groupby(spatial_group).sample(frac=frac).groupby(spatial_group).mean()
            else:
                aggregated = data[person_feat].groupby(spatial_group).mean()
        gallup_score = COUNTY_OUTCOMES_DF[spatial_var]
        merged = pd.concat([aggregated, gallup_score], join='inner', axis=1)
        r = pearsonr(merged[person_feat], merged[spatial_var])[0]
        mse = mean_squared_error(merged[person_feat], merged[spatial_var])
        #print(f'{person_feat}: r = {r:.4f}, mse = {mse:.4f}')
        rs.append(r)
        mses.append(mse)
    return rs, mses

r_avg, mse_avg = [0]*len(person_outcomes), [0]*len(person_outcomes)
for ii in range(N_iters):
    r, mse = weighted_calculation(USER_FACTORS_AND_FEATURES_DF, frac=frac)
    r_avg = [sum(x) for x in zip(r_avg, r)]
    mse_avg = [sum(x) for x in zip(mse_avg, mse)]

r_avg = [r/float(N_iters) for r in r_avg]
mse_avg = [mse/float(N_iters) for mse in mse_avg]
for i, person_feat in enumerate(person_outcomes):
    print("""{person_feat}: r = {r:.4f}, mse = {mse:.4f}""".format(person_feat=person_feat, r=r_avg[i], mse=mse_avg[i]))

"""### ICWSM weights"""

n = -1 # number of samples to take from each county
frac = -1 # percentage (rather than count) of observations to take from each county
N_iters = 10 # number of time to do unweighted calculation

# def weighted_calculation(data, weight_col):
#     lex_features = ['DEP_SCORE', 'ANX_SCORE', 'SWB_HAPPY', 'SWB_LADDER']
#     gallup_vars = ['depression', 'worried', 'happy', 'ladder']
#     for lex_feat, gallup_var in zip(lex_features, gallup_vars):
#         weighted_users = data[lex_feat] * data[weight_col]
#         aggregated = weighted_users.groupby('cnty').mean()
#         aggregated.name = lex_feat
#         gallup_score = COUNTY_OUTCOMES_DF[gallup_var]
#         merged = pd.concat([aggregated, gallup_score], join='inner', axis=1)
#         r = pearsonr(merged[lex_feat], merged[gallup_var])[0]
#         mse = mean_squared_error(merged[lex_feat], merged[gallup_var])
#         print(f'{lex_feat}: r = {r:.4f}, mse = {mse:.4f}')

# weighted_calculation(USER_FACTORS_AND_FEATURES_DF, 'rps_weight')
weight_col = 'rps_weight'

r_avg, mse_avg = [0]*len(person_outcomes), [0]*len(person_outcomes)
for ii in range(N_iters):
    r, mse = weighted_calculation(USER_FACTORS_AND_FEATURES_DF, frac=frac, weight_col=weight_col)
    r_avg = [sum(x) for x in zip(r_avg, r)]
    mse_avg = [sum(x) for x in zip(mse_avg, mse)]

r_avg = [r/float(N_iters) for r in r_avg]
mse_avg = [mse/float(N_iters) for mse in mse_avg]
for i, person_feat in enumerate(person_outcomes):
    print("""{person_feat}: r = {r:.4f}, mse = {mse:.4f}""".format(person_feat=person_feat, r=r_avg[i], mse=mse_avg[i]))



"""## Function to get socio-demographic bins of a census and twitter"""

def get_census_bin_counts(census_data, cols):
    population = census_data['population']
    bin_counts = np.sum(census_data[cols].to_numpy() * np.tile(population, (len(cols), 1)).T  / 100, axis=0)
    return bin_counts


def get_twitter_bin_counts(user_demographics, twitter_bins):
    if len(user_demographics) == 0:
        return np.zeros(len(twitter_bins) - 1)

    bin_counts = []
    for bin1, bin2 in zip(twitter_bins, twitter_bins[1:]):
        bin_counts.append(np.sum(user_demographics.between(bin1, bin2, inclusive='left')))

    return np.array(bin_counts)

"""## Bias calculation function"""

census_counts = get_census_bin_counts(CENSUS_DEMOGRAPHICS_DF.loc[1003], CENSUS_TABLE_COLS['age'])
twitter_counts = get_twitter_bin_counts(USER_FACTORS_AND_FEATURES_DF.loc[1003, 'age'], TWITTER_BINS['age'])

entropy(census_counts, twitter_counts)

def calculate_bias_for_county(county):
    unweighted_biases = []
    rps_biases = []
    ops_biases = []

    for dem in DEMOGRAPHICS:
        census_counts = get_census_bin_counts(CENSUS_DEMOGRAPHICS_DF.loc[county], CENSUS_TABLE_COLS[dem])

        twitter_data = USER_FACTORS_AND_FEATURES_DF.loc[county]

        twitter_bins = TWITTER_BINS[dem]

        unweighted_counts = []
        rps_counts = []
        ops_counts = []

        for bin1, bin2 in zip(twitter_bins, twitter_bins[1:]):
            users = twitter_data[twitter_data[dem].between(bin1, bin2, inclusive='left')]
            unweighted_counts.append(len(users))
            rps_counts.append(users['rps_weight'].sum())
            ops_counts.append(users['ops_weight'].sum())

        unweighted_counts = np.array(unweighted_counts) + 1e-9
        rps_counts = np.array(rps_counts) + 1e-9
        ops_counts = np.array(ops_counts) + 1e-9

        unweighted_bias = entropy(census_counts, unweighted_counts)
        rps_bias = entropy(census_counts, rps_counts)
        ops_bias = entropy(census_counts, ops_counts)

        unweighted_biases.append(unweighted_bias)
        rps_biases.append(rps_bias)
        ops_biases.append(ops_bias)

    return unweighted_biases, rps_biases, ops_biases

calculate_bias_for_county(1005)

def calculate_bias(data):
    unweighted_biases = []
    rps_biases = []
    ops_biases = []
    user_counts = []

    grouped = data.groupby(spatial_group)

    for county, twitter_data in tqdm(grouped):
        unweighted_bias = []
        rps_bias = []
        ops_bias = []

        for dem in DEMOGRAPHICS:
            census_counts = get_census_bin_counts(CENSUS_DEMOGRAPHICS_DF.loc[county], CENSUS_TABLE_COLS[dem])

            twitter_bins = TWITTER_BINS[dem]

            unweighted_counts = []
            rps_counts = []
            ops_counts = []

            for bin1, bin2 in zip(twitter_bins, twitter_bins[1:]):
                users = twitter_data[twitter_data[dem].between(bin1, bin2, inclusive='left')]
                unweighted_counts.append(len(users))
                rps_counts.append(users['rps_weight'].sum())
                ops_counts.append(users['ops_weight'].sum())

            unweighted_counts = np.array(unweighted_counts) + 1e-9
            rps_counts = np.array(rps_counts) + 1e-9
            ops_counts = np.array(ops_counts) + 1e-9

            unweighted_dem_bias = entropy(census_counts, unweighted_counts)
            rps_dem_bias = entropy(census_counts, rps_counts)
            ops_dem_bias = entropy(census_counts, ops_counts)

            unweighted_bias.append(unweighted_dem_bias)
            rps_bias.append(rps_dem_bias)
            ops_bias.append(ops_dem_bias)

        unweighted_biases.append(unweighted_bias)
        rps_biases.append(rps_bias)
        ops_biases.append(ops_bias)

        user_counts.append(len(twitter_data))

    unweighted_biases1 = np.average(unweighted_biases, axis=0)
    rps_biases1 = np.average(rps_biases, axis=0)
    ops_biases1 = np.average(ops_biases, axis=0)

    unweighted_biases2 = np.average(unweighted_biases, axis=0, weights=user_counts)
    rps_biases2 = np.average(rps_biases, axis=0, weights=user_counts)
    ops_biases2 = np.average(ops_biases, axis=0, weights=user_counts)

    print()
    print('=== unweighted average ===')
    print('unweighted bias:', unweighted_biases1)
    print('rps bias:       ', rps_biases1)
    print('ops bias:       ', ops_biases1)
    print('=== weighted average ===')
    print('unweighted bias:', unweighted_biases2)
    print('rps bias:       ', rps_biases2)
    print('ops bias:       ', ops_biases2)

calculate_bias(USER_FACTORS_AND_FEATURES_DF)

"""## Function to one-hot encode each user socio-demographics"""

def get_user_demographic_embeddings(user_demographics, twitter_bins):
    dem_binned = age_binned = pd.cut(user_demographics, bins=twitter_bins, right=False, labels=False)
    one_hot_encoding = np.eye(len(twitter_bins) - 1)[dem_binned]
    return one_hot_encoding

def percentage_multi_hot_encoding(percentages):
    # percentages: [age_bins (11), inc_bins (10), gen_bins (2), edu_bins (2)]
    # encoding: (|age_bins| + |inc_bins| + |gen_bins| + |edu_bins|)
    return torch.concat(percentages, axis=0)

def embeddings_multi_hot_encoding(embeddings):
    # percentages: [age_bins (u, 11), inc_bins (u, 10), gen_bins (u, 2), edu_bins (u, 2)]
    # encoding: (u, |age_bins| + |inc_bins| + |gen_bins| + |edu_bins|)
    return np.concatenate(embeddings, axis=1)

def percentage_one_hot_encoding(percentages):
    # percentages: [age_bins (11), inc_bins (10), gen_bins (2), edu_bins (2)]
    # encoding: (|age_bins| * |inc_bins| * |gen_bins| * |edu_bins|)
    encoding = percentages[0]
    for p in percentages[1:]:
        encoding = torch.outer(encoding, p).ravel()
    return encoding

@jit(nopython=True)
def embeddings_one_hot_encoding(embeddings):
    # percentages: [age_bins (u, 11), inc_bins (u, 10), gen_bins (u, 2), edu_bins (u, 2)]
    # encoding: (u, |age_bins| * |inc_bins| * |gen_bins| * |edu_bins|)
    encoding = embeddings[0]
    num_users = len(encoding)
    for e in embeddings[1:]:
        new_dim = len(encoding[0]) * len(e[0])
        new_encoding = np.zeros((num_users, new_dim))
        for i in range(num_users):
            x = encoding[i]
            y = e[i]
            cross = np.outer(x, y).ravel()
            new_encoding[i] = cross
        encoding = new_encoding
        # encoding = [np.outer(encoding[i], e[i]).ravel() for i in range(num_users)]
    return encoding

"""## Dataloader"""

def load_data(demographics, dem_census_cols, dem_twitter_bins, features, outcomes):
    assert len(demographics) == len(dem_census_cols) and len(demographics) == len(dem_twitter_bins)

    grouped = USER_FACTORS_AND_FEATURES_DF.groupby(spatial_group)

    user_ids = []
    user_features = {f: [] for f in features}
    census_bin_counts = []
    twitter_bin_counts = []
    user_dem_embeddings = []
    county_outcomes = {o: [] for o in outcomes}

    for county, twitter_data in tqdm(grouped):
        try:
            census_data = CENSUS_DEMOGRAPHICS_DF.loc[county]
            gallup_data = COUNTY_OUTCOMES_DF.loc[county]
        except:
            continue

        # user_ids: (|users_in_county|)
        county_user_ids = twitter_data['user_id'].to_numpy()
        user_ids.append(county_user_ids)

        # user_features: (DEP_SCORE, ANX_SCORE, SWB_HAPPY, SWB_LADDER)
        for f in features:
            county_user_features = twitter_data[f].to_numpy()
            user_features[f].append(county_user_features)

        # census_bin_counts: (|age_bins| + |inc_bins| + |gen_bins| + |edu_bins|)
        # twitter_bin_counts: (|age_bins| + |inc_bins| + |gen_bins| + |edu_bins|)
        # user_dem_embeddings: (u, |age_bins| + |inc_bins| + |gen_bins| + |edu_bins|)
        county_census_bin_counts = []
        county_twitter_bin_counts = []
        county_user_dem_embeddings = []
        for dem, census_cols, twitter_bins in zip(demographics, dem_census_cols, dem_twitter_bins):
            dem_census_bin_counts = get_census_bin_counts(census_data, census_cols)
            dem_twitter_bin_counts = get_twitter_bin_counts(twitter_data[dem], twitter_bins)
            one_hot_encodings = get_user_demographic_embeddings(twitter_data[dem], twitter_bins)

            county_census_bin_counts.append(dem_census_bin_counts)
            county_twitter_bin_counts.append(dem_twitter_bin_counts)
            county_user_dem_embeddings.append(one_hot_encodings)

        # county_census_bin_counts = np.concatenate(county_census_bin_counts, axis=0)
        census_bin_counts.append(county_census_bin_counts)
        # county_twitter_bin_counts = np.concatenate(county_twitter_bin_counts, axis=0)
        twitter_bin_counts.append(county_twitter_bin_counts)
        # county_user_dem_embeddings = np.concatenate(county_user_dem_embeddings, axis=1)
        user_dem_embeddings.append(county_user_dem_embeddings)

        # county_outcomes: (depression, worried, happy, ladder)
        for o in outcomes:
            gallup_score = gallup_data[o]
            county_outcomes[o].append(gallup_score)

    return user_ids, user_features, census_bin_counts, twitter_bin_counts, user_dem_embeddings, county_outcomes

# features = ['DEP_SCORE', 'ANX_SCORE', 'SWB_HAPPY', 'SWB_LADDER']
# outcomes = ['depression', 'worried', 'happy', 'ladder']
# dem_census_cols = [CENSUS_TABLE_COLS['age'], CENSUS_TABLE_COLS['inc'], CENSUS_TABLE_COLS['gen'], CENSUS_TABLE_COLS['edu']]
# dem_twitter_bins = [TWITTER_BINS['age'], TWITTER_BINS['inc'], TWITTER_BINS['gen'], TWITTER_BINS['edu']]

dem_census_cols = [CENSUS_TABLE_COLS[dem] for dem in DEMOGRAPHICS]
dem_twitter_bins = [TWITTER_BINS[dem] for dem in DEMOGRAPHICS]

user_ids, user_features, census_bin_counts, twitter_bin_counts, user_dem_embeddings, county_outcomes = load_data(DEMOGRAPHICS, dem_census_cols, dem_twitter_bins, person_outcomes, spatial_outcomes)

print(type(user_ids), len(user_ids))
print(type(user_features), len(user_features), list(user_features.keys()))
print(type(user_features['DEP_SCORE']), len(user_features['DEP_SCORE']))
print(type(census_bin_counts), len(census_bin_counts))
print(type(twitter_bin_counts), len(twitter_bin_counts))
print(type(user_dem_embeddings), len(user_dem_embeddings))
print(type(county_outcomes), len(county_outcomes), list(county_outcomes.keys()))

X_dep = list(zip(user_ids, user_features['DEP_SCORE'], census_bin_counts, twitter_bin_counts, user_dem_embeddings))
X_anx = list(zip(user_ids, user_features['ANX_SCORE'], census_bin_counts, twitter_bin_counts, user_dem_embeddings))
X_happy = list(zip(user_ids, user_features['SWB_HAPPY'], census_bin_counts, twitter_bin_counts, user_dem_embeddings))
X_ladder = list(zip(user_ids, user_features['SWB_LADDER'], census_bin_counts, twitter_bin_counts, user_dem_embeddings))

y_dep = county_outcomes['depression']
y_anx = county_outcomes['worried']
y_happy = county_outcomes['happy']
y_ladder = county_outcomes['ladder']

print(X_dep[0][0].shape) # user_ids
print(X_dep[0][1].shape) # user_scores (DEP_SCORE)
print(len(X_dep[0][2]), X_dep[0][2][0].shape) # census_bin_counts
print(len(X_dep[0][3]), X_dep[0][3][0].shape) # twitter_bin_counts
print(len(X_dep[0][4]), X_dep[0][4][0].shape) # user_embeddings

"""## Training scripts and model"""

def bin_percents(x, bins):
    percents = torch.zeros(len(bins) - 1, device=DEVICE)

    for i in range(len(percents)):
        bin1 = bins[i]
        bin2 = bins[i + 1]
        size = bin2 - bin1
        # mask = ((x >= bin1) & (x < bin2)).float()
        mask = F.relu(x - bin1) * F.relu(bin2 - x)
        masked = x * mask
        percents[i] += torch.sum(torch.abs(masked / (torch.abs(masked) + 1e-3)))

    return percents / percents.sum()


def pearsonr_loss(y_pred, y_true):
    vx = y_pred - torch.mean(y_pred)
    vy = y_true - torch.mean(y_true)
    loss = torch.sum(vx * vy) / (torch.sqrt(torch.sum(vx ** 2)) * torch.sqrt(torch.sum(vy ** 2)))
    return -loss


def train(model, X, y, optimizer, loss_type='pearsonr'):
    model.train()
    optimizer.zero_grad()
    y_tensor = torch.tensor(y, dtype=torch.float32, device=DEVICE) # (N)

    # out = model(X) # (N)
    out = model(X)
    if loss_type == 'mse':
        loss = F.mse_loss(out, y_tensor)
    elif loss_type == 'pearsonr':
        loss = pearsonr_loss(out, y_tensor)
    elif loss_type == 'custom':
        loss1 = pearsonr_loss(out, y_tensor)
        loss2 = torch.sum(torch.log(out / y_tensor))
        loss = loss1 + loss2

    loss.backward()
    optimizer.step()

    y_pred = out.cpu().detach().numpy()
    r2 = r2_score(y_pred, y)
    r = pearsonr(y_pred, y)
    mse = mean_squared_error(y_pred, y)

    return r, r2, mse


def test(model, X, y):
    model.eval()
    y_tensor = torch.tensor(y, dtype=torch.float32, device=DEVICE)

    with torch.no_grad():
        out = model(X)

    y_pred = out.cpu().numpy()
    r2 = r2_score(y_pred, y)
    r = pearsonr(y_pred, y)
    mse = mean_squared_error(y_pred, y)

    return r, r2, mse

class PS_NN(nn.Module):
    def __init__(self, num_factors=25, num_dem=4, use_smoothing=None, combine='multi-hot', distance='l1'):
        super().__init__()
        # parameters
        self.num_factors = num_factors
        self.num_dem = num_dem
        self.use_smoothing = use_smoothing.lower() if use_smoothing else ''
        self.combine = combine.lower() if combine else ''
        self.distance = distance.lower() if distance else ''

        if self.use_smoothing == 'constant':
            self.smoothing = torch.tensor([10.], device=DEVICE)
        elif self.use_smoothing == 'single':
            self.smoothing = nn.Parameter(torch.tensor([10.], requires_grad=True)).to(DEVICE)
            self.smoothing2 = nn.Parameter(torch.tensor([10.], requires_grad=True)).to(DEVICE)
        elif self.use_smoothing == 'multiple':
            self.smoothing = nn.Parameter(torch.tensor([10.] * self.num_dem, requires_grad=True)).to(DEVICE)
            self.smoothing2 = nn.Parameter(torch.tensor([10.] * self.num_dem, requires_grad=True)).to(DEVICE)
        else:
            self.smoothing = torch.zeros(1, device=DEVICE)

        if self.combine not in ('multi-hot', 'one-hot', 'both'):
            raise ValueError(f'invalid combine: {combine}')

        # weights
        # self.hidden1 = nn.Linear(num_factors, num_factors)
        # self.hidden2 = nn.Linear(num_factors, num_factors)
        self.fc1 = nn.Linear(num_factors, 1)

    def forward(self, x, return_weights=False):
        # x is a list of tuples containing user_ids, user_scores, census_bin_counts, twitter_bin_counts[0:f], user_embeddings for all counties
        # |x| = number of counties N
        # x[j] = (user_ids[0:u], user_scores[0:u], census_bin_counts[0:f], twitter_bin_counts[0:f], user_embeddings[0:u, 0:f])
        # |x[j]| = number of users M_N in county j
        county_weighted_avgs = []
        all_user_ids = []
        all_user_weights = []
        all_kls = []
        user_counts = []

        for data in tqdm(x):
            user_scores = data[1] # (u)
            census_bin_counts = data[2] # [(11), (10), (2), (2)]
            twitter_bin_counts = data[3] # [(11), (10), (2), (2)]
            user_dems = data[4] # [(u, 11), (u, 10), (u, 2), (u, 2)]

            # convert to tensors
            user_scores = torch.tensor(user_scores, dtype=torch.float32, device=DEVICE) # (u)
            census_bin_percents = [torch.tensor(x / np.sum(x), dtype=torch.float32, device=DEVICE) for x in census_bin_counts] # [(11), (10), (2), (2)]
            twitter_bin_counts = [torch.tensor(x, dtype=torch.float32, device=DEVICE) for x in twitter_bin_counts] # [(11), (10), (2), (2)]
            twitter_bin_percents = [0] * self.num_dem

            # informed smoothing
            for i in range(self.num_dem):
                if self.use_smoothing == 'multiple':
                    smoothing = self.smoothing[i]
                    smoothing2 = self.smoothing2[i]
                    twitter_bin_percents[i] = (twitter_bin_counts[i] + smoothing * census_bin_percents[i]) / torch.sum(twitter_bin_counts[i] + smoothing) # (num_factors)
                    twitter_bin_percents[i] = torch.sigmoid(smoothing2 * twitter_bin_percents[i])
                elif self.use_smoothing in ('constant', 'single'):
                    smoothing = self.smoothing
                    smoothing2 = self.smoothing2
                    twitter_bin_percents[i] = (twitter_bin_counts[i] + smoothing * census_bin_percents[i]) / torch.sum(twitter_bin_counts[i] + smoothing) # (num_factors)
                    twitter_bin_percents[i] = torch.sigmoid(smoothing2 * twitter_bin_percents[i])
                else:
                    twitter_bin_percents[i] = twitter_bin_counts[i] / torch.sum(twitter_bin_counts[i]) # (num_factors)

            # combine
            if self.combine == 'multi-hot':
                census_encoding = percentage_multi_hot_encoding(census_bin_percents) # (num_factors)
                twitter_encoding = percentage_multi_hot_encoding(twitter_bin_percents) # (num_factors)
                user_encodings = embeddings_multi_hot_encoding(user_dems) # (u, num_factors)
            elif self.combine == 'one-hot':
                census_encoding = percentage_one_hot_encoding(census_bin_percents) # (num_factors)
                twitter_encoding = percentage_one_hot_encoding(twitter_bin_percents) # (num_factors)
                user_encodings = embeddings_one_hot_encoding(user_dems) # (u, num_factors)
            elif self.combine == 'both':
                census_encoding1 = percentage_multi_hot_encoding(census_bin_percents)
                census_encoding2 = percentage_multi_hot_encoding(census_bin_percents)
                census_encoding = torch.concat([census_encoding1, census_encoding2], axis=0) # (num_factors)

                twitter_encoding1 = percentage_one_hot_encoding(twitter_bin_percents)
                twitter_encoding2 = percentage_one_hot_encoding(twitter_bin_percents)
                twitter_encoding = torch.concat([twitter_encoding1, twitter_encoding2], axis=0) # (num_factors)

                user_encodings1 = embeddings_multi_hot_encoding(user_dems)
                user_encodings2 = embeddings_one_hot_encoding(user_dems)
                user_encodings = np.concatenate([user_encodings1, user_encodings2], axis=1) # (u, num_factors)

            # convert to tensor
            user_encodings = torch.tensor(user_encodings, dtype=torch.float32, device=DEVICE) # (u, num_factors)

            # distance metric
            if self.distance == 'l1':
                user_features = torch.abs(twitter_encoding - census_encoding) * user_encodings # (u, num_factors)
            elif self.distance == 'l2':
                user_features = torch.square(twitter_encoding - census_encoding) * user_encodings # (u, num_factors)
            else:
                user_features = (twitter_encoding - census_encoding) * user_encodings # (u, num_factors)

            # user_features = self.hidden1(user_features) # (u, num_factors)
            # user_features = F.relu(user_features)
            # user_features = self.hidden2(user_features) # (u, num_factors)
            # user_features = F.relu(user_features)
            user_features = self.fc1(user_features) # (u, 1)
            user_weights = F.softmax(user_features, dim=0) * len(user_features) # (u, 1)

            if return_weights:
                all_user_ids.append(data[0])
                all_user_weights.append(user_weights.detach().squeeze().cpu().numpy())

            county_weighted_avg = torch.sum(user_weights.squeeze() * user_scores) / torch.sum(user_weights) # (1)
            county_weighted_avgs.append(county_weighted_avg)

        county_weighted_avgs = torch.stack(county_weighted_avgs)
        if return_weights:
            all_user_ids = np.concatenate(all_user_ids)
            all_user_weights = np.concatenate(all_user_weights)
            weights = pd.DataFrame({'user_id': all_user_ids, 'ops_weight': all_user_weights})
            return county_weighted_avgs, weights
        else:
            return county_weighted_avgs


def train_model(model, X, y, epochs=100, lr=0.1, patience=3, decays=1, random_state=None, loss_type='pearsonr', metric_type='pearsonr',
                keep_frac=-1):
    optimizer = optim.Adam(model.parameters(), lr=lr)

    X_train_all, X_test, y_train_all, y_test = train_test_split(X, y, test_size=0.2, random_state=random_state)
    print(f'Train size = {len(y_train_all)}, Test size = {len(y_test)}')

    train_rs, train_mses = [], []
    test_rs, test_mses = [], []
    best_metric = -np.inf
    no_metric_change = 0
    total_decays = 0
    best_state = deepcopy(model.state_dict())
    for e in range(epochs):
        print(f'=== Epoch {e + 1} ===')
        if keep_frac > 0:
            X_train, y_train = shuffle(X_train_all, y_train_all, n_samples=int(keep_frac*len(y_train_all)))
            print(f'Train size = {len(y_train)}, Test size = {len(y_test)}')
        else:
            X_train, y_train = shuffle(X_train_all, y_train_all)

        (train_r, train_p), train_r2, train_mse = train(model, X_train, y_train, optimizer, loss_type)
        (test_r, test_p), test_r2, test_mse = test(model, X_test, y_test)
        print(f'Train | r = {train_r:.4f} (p = {train_p:.3e}), MSE = {train_mse:.4f}')
        print(f'Test  | r = {test_r:.4f} (p = {test_p:.3e}), MSE = {test_mse:.4f}')

        if metric_type == 'pearsonr':
            test_metric = test_r
        elif metric_type == 'mse':
            test_metric = -test_mse
        else:
            raise ValueError(f'invalid test metric: {metric_type}')

        if test_metric > best_metric:
            best_metric = test_metric
            no_metric_change = 0
            best_state = deepcopy(model.state_dict())
        else:
            no_metric_change += 1
            if no_metric_change > patience:
                total_decays += 1
                if total_decays > decays:
                    print('early stopping')
                    break
                print('decaying learning rate')
                model.load_state_dict(best_state)
                for g in optimizer.param_groups:
                    g['lr'] /= 10
                no_metric_change = 0

        train_rs.append(train_r)
        train_mses.append(train_mse)
        test_rs.append(test_r)
        test_mses.append(test_mse)

    model.load_state_dict(best_state)
    return train_rs, train_mses, test_rs, test_mses


def create_plot(feature, outcome, train_rs, train_mses, test_rs, test_mses):
    fig, ax = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle(f'{feature} model for {outcome} predictions')
    ax[0].plot(train_rs, label='train')
    ax[0].plot(test_rs, label='test')
    ax[0].legend()
    ax[0].set_xlabel('Epoch')
    ax[0].set_ylabel('Pearson r')
    ax[1].plot(train_mses, label='train')
    ax[1].plot(test_mses, label='test')
    ax[1].legend()
    ax[1].set_xlabel('Epoch')
    ax[1].set_ylabel('MSE')
    plt.show()

len(X_ladder[2])

"""## Train models

life satisfaction
"""

N_iters = 10
keep_frac = .5

results_r, results_mse = [], []
for ii in range(N_iters):
    model_ladder = PS_NN(num_factors=25, use_smoothing='multiple', combine='multi-hot', distance='l1').to(DEVICE)
    train_rs, train_mses, test_rs, test_mses = train_model(model_ladder, X_ladder, y_ladder, loss_type='pearsonr', keep_frac=keep_frac)
    clear_output()
    best_epoch = np.argmax(test_rs)
    print(f'best epoch = {best_epoch} | r = {test_rs[best_epoch]:.4f}, MSE = {test_mses[best_epoch]:.4f}')
    create_plot('SWB_LADDER', 'ladder', train_rs, train_mses, test_rs, test_mses)
    results_r.append(test_rs[best_epoch])
    results_mse.append(test_mses[best_epoch])
print(ii, np.mean(results_r), np.mean(results_mse))
# best epoch = 17 | r = 0.4097, MSE = 2.1176

# 30%
# best epoch = 24 | r = 0.3722, MSE = 2.1270

# 5%
# best epoch = 11 | r = 0.4476, MSE = 2.5720
# best epoch = 39 | r = 0.3835, MSE = 1.8840
# best epoch = 17 | r = 0.4542, MSE = 2.3005
# best epoch = 84 | r = 0.4368, MSE = 2.1555
# 0.41280352104848916 1.9574727439945387

with torch.no_grad():
    _, weights = model_ladder(X_ladder, return_weights=True)

data = USER_FACTORS_AND_FEATURES_DF[['user_id'] + DEMOGRAPHICS + ['rps_weight']].reset_index().merge(weights, on='user_id', how='left')
# data = USER_FACTORS_AND_FEATURES_DF.reset_index().drop(columns=['ops_weight']).merge(weights, on='user_id', how='left').set_index(spatial_group)
calculate_bias(data)
# weighted_calculation(data, 'ops_weight')

"""happiness"""

results_r, results_mse = [], []
for ii in range(N_iters):
    model_happy = PS_NN(num_factors=25, use_smoothing='multiple', combine='multi-hot', distance='l1').to(DEVICE)
    train_rs, train_mses, test_rs, test_mses = train_model(model_happy, X_happy, y_happy)
    clear_output()
    best_epoch = np.argmax(test_rs)
    print(f'best epoch = {best_epoch} | r = {test_rs[best_epoch]:.4f}, MSE = {test_mses[best_epoch]:.4f}')
    create_plot('SWB_HAPPY', 'happiness', train_rs, train_mses, test_rs, test_mses)

    results_r.append(test_rs[best_epoch])
    results_mse.append(test_mses[best_epoch])
print(ii, np.mean(results_r), np.mean(results_mse))

with torch.no_grad():
    _, weights = model_happy(X_happy, return_weights=True)

data = USER_FACTORS_AND_FEATURES_DF[['user_id'] + DEMOGRAPHICS + ['rps_weight']].reset_index().merge(weights, on='user_id', how='left')
calculate_bias(data)

"""depression"""

results_r, results_mse = [], []
for ii in range(N_iters):
    model_dep = PS_NN(num_factors=25, use_smoothing='single', combine='multi-hot', distance='l1').to(DEVICE)
    train_rs, train_mses, test_rs, test_mses = train_model(model_dep, X_dep, y_dep)
    clear_output()
    best_epoch = np.argmax(test_rs)
    print(f'best epoch = {best_epoch} | r = {test_rs[best_epoch]:.4f}, MSE = {test_mses[best_epoch]:.4f}')
    create_plot('DEP_SCORE', 'depression', train_rs, train_mses, test_rs, test_mses)

    results_r.append(test_rs[best_epoch])
    results_mse.append(test_mses[best_epoch])
print(ii, np.mean(results_r), np.mean(results_mse))

with torch.no_grad():
    _, weights = model_dep(X_dep, return_weights=True)

data = USER_FACTORS_AND_FEATURES_DF[['user_id'] + DEMOGRAPHICS + ['rps_weight']].reset_index().merge(weights, on='user_id', how='left')
calculate_bias(data)

"""anxiety"""

results_r, results_mse = [], []
for ii in range(N_iters):
    model_anx = PS_NN(num_factors=25, use_smoothing='single', combine='multi-hot', distance='l1').to(DEVICE)
    train_rs, train_mses, test_rs, test_mses = train_model(model_anx, X_anx, y_anx)
    clear_output()
    best_epoch = np.argmax(test_rs)
    print(f'best epoch = {best_epoch} | r = {test_rs[best_epoch]:.4f}, MSE = {test_mses[best_epoch]:.4f}')
    create_plot('DEP_SCORE', 'depression', train_rs, train_mses, test_rs, test_mses)

    results_r.append(test_rs[best_epoch])
    results_mse.append(test_mses[best_epoch])
print(ii, np.mean(results_r), np.mean(results_mse))

with torch.no_grad():
    _, weights = model_dep(X_anx, return_weights=True)

data = USER_FACTORS_AND_FEATURES_DF[['user_id'] + DEMOGRAPHICS + ['rps_weight']].reset_index().merge(weights, on='user_id', how='left')
calculate_bias(data)

# life satisfaction
results_r, results_mse = [], []
for ii in range(N_iters):
    model_ladder = PS_NN(num_factors=25, use_smoothing='multiple', combine='multi-hot', distance='l1').to(DEVICE)
    train_rs, train_mses, test_rs, test_mses = train_model(model_ladder, X_ladder, y_ladder, keep_05=True)
    clear_output()
    best_epoch = np.argmax(test_rs)
    print(f'best epoch = {best_epoch} | r = {test_rs[best_epoch]:.4f}, MSE = {test_mses[best_epoch]:.4f}')
    create_plot('SWB_LADDER', 'ladder', train_rs, train_mses, test_rs, test_mses)
    results_r.append(test_rs[best_epoch])
    results_mse.append(test_mses[best_epoch])
print(ii, np.mean(results_r), np.mean(results_mse))

# happiness
results_r, results_mse = [], []
for ii in range(N_iters):
    model_happy = PS_NN(num_factors=25, use_smoothing='multiple', combine='multi-hot', distance='l1').to(DEVICE)
    train_rs, train_mses, test_rs, test_mses = train_model(model_happy, X_happy, y_happy, keep_05=True)
    clear_output()
    best_epoch = np.argmax(test_rs)
    print(f'best epoch = {best_epoch} | r = {test_rs[best_epoch]:.4f}, MSE = {test_mses[best_epoch]:.4f}')
    create_plot('SWB_HAPPY', 'happiness', train_rs, train_mses, test_rs, test_mses)

    results_r.append(test_rs[best_epoch])
    results_mse.append(test_mses[best_epoch])
print(ii, np.mean(results_r), np.mean(results_mse))

# depression
results_r, results_mse = [], []
for ii in range(N_iters):
    model_dep = PS_NN(num_factors=25, use_smoothing='single', combine='multi-hot', distance='l1').to(DEVICE)
    train_rs, train_mses, test_rs, test_mses = train_model(model_dep, X_dep, y_dep, keep_05=True)
    clear_output()
    best_epoch = np.argmax(test_rs)
    print(f'best epoch = {best_epoch} | r = {test_rs[best_epoch]:.4f}, MSE = {test_mses[best_epoch]:.4f}')
    create_plot('DEP_SCORE', 'depression', train_rs, train_mses, test_rs, test_mses)

    results_r.append(test_rs[best_epoch])
    results_mse.append(test_mses[best_epoch])
print(ii, np.mean(results_r), np.mean(results_mse))

# anxiety
results_r, results_mse = [], []
for ii in range(N_iters):
    model_anx = PS_NN(num_factors=25, use_smoothing='single', combine='multi-hot', distance='l1').to(DEVICE)
    train_rs, train_mses, test_rs, test_mses = train_model(model_anx, X_anx, y_anx, keep_05=True)
    clear_output()
    best_epoch = np.argmax(test_rs)
    print(f'best epoch = {best_epoch} | r = {test_rs[best_epoch]:.4f}, MSE = {test_mses[best_epoch]:.4f}')
    create_plot('DEP_SCORE', 'depression', train_rs, train_mses, test_rs, test_mses)

    results_r.append(test_rs[best_epoch])
    results_mse.append(test_mses[best_epoch])
print(ii, np.mean(results_r), np.mean(results_mse))

"""## garbage collection"""

torch.cuda.empty_cache()
gc.collect()